# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'mipantalla.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from base_datos import conn

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 514)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # QLineEdit para ingresar el nombre del equipo de futbol.
        self.nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.nombre.setGeometry(QtCore.QRect(145, 80, 150, 23))
        self.nombre.setObjectName("nombre")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 80, 54, 15))
        self.label.setObjectName("label")

        # QLineEdit para ingresar siglas de equipos
        self.siglas = QtWidgets.QLineEdit(self.centralwidget)
        self.siglas.setGeometry(QtCore.QRect(145, 110, 150, 23))
        self.siglas.setObjectName("siglas")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 64, 25))
        self.label_2.setObjectName("label2")
        
        # QLineEdit para ingresar seguidores
        self.seguidores = QtWidgets.QLineEdit(self.centralwidget)
        self.seguidores.setGeometry(QtCore.QRect(145, 140, 150, 25))
        self.seguidores.setText("")
        self.seguidores.setObjectName("seguidores")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 140, 74, 15))
        self.label_3.setObjectName("label_3")

        # QLineEdit para ingresar campeonatos obtenidos
        self.campeonatos = QtWidgets.QLineEdit(self.centralwidget)
        self.campeonatos.setGeometry(QtCore.QRect(145, 170, 150, 25))
        self.campeonatos.setText("")
        self.campeonatos.setObjectName("campeonatos")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 170, 74, 25))
        self.label_4.setObjectName("label_4")

        # QLineEdit para ingresar estadios
        self.estadio = QtWidgets.QLineEdit(self.centralwidget)
        self.estadio.setGeometry(QtCore.QRect(145, 200, 150, 23))
        self.estadio.setObjectName("estadio")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 200, 54, 15))
        self.label_5.setObjectName("label_5")

        # Botón denominado “Guardar” para almacenar información de los equipos
        self.guardar = QtWidgets.QPushButton(self.centralwidget)
        self.guardar.setGeometry(QtCore.QRect(70, 240, 220,25))
        self.guardar.setObjectName("guardar")

        # Botón actualizar para refrescar los datos de los equipos.
        self.actualizar = QtWidgets.QPushButton(self.centralwidget)
        self.actualizar.setGeometry(QtCore.QRect(70, 272, 220, 25))
        self.actualizar.setObjectName("actualizar")

        # QTableWidget para mostrar una lista de equipos
        self.listacampeonato_equipos = QtWidgets.QTableWidget(self.centralwidget)
        self.listacampeonato_equipos.setGeometry(QtCore.QRect(370, 70, 556, 192))
        self.listacampeonato_equipos.setObjectName("listacampeonato_equipos")
        self.listacampeonato_equipos.setColumnCount(0)
        self.listacampeonato_equipos.setRowCount(0)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        # guardar
        self.crear_base()
        self.obtener_informacion()
        self.guardar.clicked.connect(self.guardar_informacion)
        self.actualizar.clicked.connect(self.obtener_informacion)
        # Método establece el texto de las etiquetas y los botones según la traducción de idioma proporcionada
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    #   Método establece el texto de las etiquetas y los botones según la traducción de idioma proporcionada 
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Equipos Futbol", "Equipos Futbol"))
        self.label.setText(_translate("MainWindow", "Nombre:"))
        self.label_2.setText(_translate("MainWindow", "Siglas:"))
        self.label_3.setText(_translate("MainWindow", "Seguidores:"))
        self.label_4.setText(_translate("MainWindow", "Campeonatos:"))
        self.label_5.setText(_translate("MainWindow", "Estadio:"))
        self.guardar.setText(_translate("MainWindow", "Guardar"))
        self.actualizar.setText(_translate("MainWindow", "Actualizar"))

    # Intenta crear una tabla llamada "campeonato_equipo" en la base de datos si aún no existe.
    def crear_base(self):
        cursor = conn.cursor()
        cadena_sql = 'CREATE TABLE campeonato_equipo (nombre TEXT, siglas TEXT, seguidores INTEGER, campeonatos INTEGER, estadio TEXT)'
        try:
            cursor.execute(cadena_sql)
        except:
            pass
        cursor.close()

    # Se activa cuando se hace clic en el botón "Guardar"
    def guardar_informacion(self):
        cursor = conn.cursor()
        nombre = str(self.nombre.text())
        siglas = str(self.siglas.text())
        seguidores = int(self.seguidores.text())
        campeonatos = int(self.campeonatos.text())
        estadio = str(self.estadio.text())

        cadena_sql = """INSERT INTO campeonato_equipo (nombre, siglas, seguidores, campeonatos, estadio) VALUES ('%s', '%s', %d, %d, '%s');""" % \
    (nombre, siglas, seguidores, campeonatos, estadio)
        # ejecutar el SQL
        cursor.execute(cadena_sql)
        # confirmar los cambios
        conn.commit()
        cursor.close()

    # Se activa cuando se hace clic en el botón "Actualizar" o cuando se inicia la aplicación.
    def obtener_informacion(self):
        cursor = conn.cursor()
        cadena_consulta_sql = "SELECT * from campeonato_equipo"    # Actualiza consulta
        cursor.execute(cadena_consulta_sql)
        informacion = cursor.fetchall()
        database_table_column_count = 5
        self.listacampeonato_equipos.setColumnCount(database_table_column_count)
        numero_filas = len(informacion) #Obtener el número de elementos de una lista 
        self.listacampeonato_equipos.setRowCount(numero_filas)
        for j in range(numero_filas):
            valor = informacion[j]
            for i in range(0, len(valor)):
                elemento = valor[i]
                elemento = str(elemento)
                nuevo_registro = QtWidgets.QTableWidgetItem(elemento)
                self.listacampeonato_equipos.setItem(j, i, nuevo_registro)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())