# Generated by Django 4.1.5 on 2023-01-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('siglas', models.CharField(max_length=30)),
                ('seguidores', models.IntegerField()),
                ('campeonatos', models.IntegerField()),
                ('estadio', models.CharField(max_length=100)),
            ],
        ),
    ]
