# Generated by Django 5.0.7 on 2024-07-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipo_futbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('colores', models.CharField(max_length=30)),
                ('plantilla_jugadores', models.IntegerField()),
                ('rentabilidad', models.IntegerField()),
                ('estadio', models.CharField(max_length=100)),
            ],
        ),
    ]
